server:
  port: 9030

spring:
  datasource: 
    url: jdbc:postgresql:://localhost:5433/razorpay-merchant-db

app:
  webhook:
    delivery:
      redis-key: "webhook-retry"
      poll-batch-size: 100